// Renders docs/QUERIES.md from the catalog. catalog.test.ts compares the result
// with the file on disk, so the doc fails CI the moment it stops matching the
// code, and `npm test -- -u` rewrites it.
import { PREFIXES } from '../../constants/prefixes';
import { pretty, type CatalogEntry } from './catalog';
import type { PrebuiltQuery } from '../../constants/prebuiltQueries';
import type { EntityBlock } from '../../types/query';

// One worked example per relationship. Samples and facilities in Maine because
// that pairing is the app's most common question and Maine has the most data.
const EXAMPLES: Array<[string, string]> = [
  ['samples near facilities [ME on A]', 'Samples near facilities in Maine'],
  ['samples downstream facilities [ME on A]', 'Samples downstream of facilities in Maine'],
  ['samples upstream facilities [ME on A]', 'Samples upstream from facilities in Maine'],
  ['samples downstream(30km) facilities [ME on A]', 'Samples downstream of facilities in Maine, within 30 km of flow'],
];

const ENTITY_LABELS: Array<[string, string]> = [
  ['samples', 'Samples'],
  ['facilities', 'Facilities'],
  ['waterBodies', 'Water bodies'],
  ['wells', 'Wells'],
  ['aquifers', 'Aquifers'],
  ['streams', 'Streams'],
];

const STEP_TYPES: Array<[string, string]> = [
  ['FIND_TARGET_IRIS', 'Finds the identifiers of the entities the question is asking for.'],
  ['FIND_ANCHOR_IRIS', 'Finds the identifiers of the entities on the other side of the relationship that matched.'],
  ['GET_FLOWLINE_GEOMETRIES', 'Downstream and upstream only: the river segments connecting the two sides, drawn as the stream layer.'],
  ['HYDRATE_TARGET_BY_IRI', 'Loads names, geometry and properties for the identifiers the first step found.'],
  ['HYDRATE_ANCHOR_BY_IRI', 'The same for the other side.'],
  ['GET_REGION_BOUNDARIES', 'The outline of the selected state or counties. Skipped when no region is set.'],
];

const fence = (query: string) => ['```sparql', pretty(query), '```'];

export function renderQueriesDoc(entries: CatalogEntry[]): string {
  const byName = new Map(entries.map((e) => [e.name, e]));
  const get = (name: string) => {
    const entry = byName.get(name);
    if (!entry) throw new Error(`docs/QUERIES.md refers to a catalog entry that does not exist: ${name}`);
    return entry;
  };
  const analysisCount = entries.filter((e) => e.question).length;
  const out: string[] = [
    '# SPARQL queries',
    '',
    '<!-- Generated by src/engine/queries/catalog.test.ts from src/engine/queries/catalog.ts. Do not edit by hand: run `npm test -- -u`. -->',
    '',
    'Every query the explorer sends, generated from the code that sends it. CI fails when this file',
    'no longer matches the code, so what is written here is what the app runs.',
    '',
    'Examples use Maine (state `23`, Cumberland and Penobscot counties `23005` and `23019`). Where a',
    'step receives identifiers from an earlier step, they appear as `http://example.org/...`',
    'placeholders. The PREFIX block is the same in every query, so it is left out and printed once',
    'under [Prefixes](#prefixes).',
    '',
    `This page shows ${EXAMPLES.length} worked analysis questions. The catalog has ${analysisCount}`,
    'question shapes in all; print any of them with',
    '',
    '```bash',
    'npm run sparql                                   # list every entry',
    'npm run sparql -- "wells upstream streams [ME on C]"',
    '```',
    '',
    '## Contents',
    '',
    '- [Dropdowns](#dropdowns)',
    '- [Sample popup](#sample-popup)',
    '- [Analysis questions](#analysis-questions)',
    ...EXAMPLES.map(([, title]) => `  - [${title}](#${slug(title)})`),
    '  - [Details for each entity type](#details-for-each-entity-type)',
    '- [Probes](#probes)',
    '- [Prefixes](#prefixes)',
    '',
    '## Dropdowns',
    '',
    'Each dropdown asks the graph what to offer, once per region per session (React Query,',
    '`staleTime: Infinity`). The builder and endpoint for each one are paired in',
    '`LOOKUPS` in `src/engine/lookupQueries.ts`.',
    '',
  ];

  // Group the dropdown entries by control: "Substance, state" -> "Substance".
  const dropdowns = new Map<string, CatalogEntry[]>();
  for (const e of entries.filter((x) => x.name.startsWith('DROPDOWN: '))) {
    const [control] = e.name.slice('DROPDOWN: '.length).split(', ');
    dropdowns.set(control, [...(dropdowns.get(control) ?? []), e]);
  }
  for (const [control, group] of dropdowns) {
    out.push(`### ${control}`, '', `Sent from ${group[0].usedBy}.`, '');
    for (const e of group) {
      const variant = e.name.split(', ').slice(1).join(', ');
      for (const s of e.steps) {
        const label = [variant && capitalise(variant), group[0].steps.length > 1 ? `\`${s.type}\`` : '', `on \`${s.endpoint}\``]
          .filter(Boolean)
          .join(', ');
        out.push(`#### ${capitalise(label)}`, '', ...fence(s.query), '');
      }
    }
  }

  out.push('## Sample popup', '', `Sent from ${get('POPUP: Sample point').usedBy}. One sample point at a time.`, '');
  for (const name of ['POPUP: Sample point', 'POPUP: Sample point, with sample filters']) {
    const e = get(name);
    const variant = name.includes('filters') ? 'With the question\'s sample filters (PFOS, detections only)' : 'No filters';
    out.push(`#### ${variant}, on \`${e.steps[0].endpoint}\``, '', ...fence(e.steps[0].query), '');
  }

  out.push(
    '## Analysis questions',
    '',
    'A question is two entity blocks and a relationship. `planPipeline` in `src/engine/planner.ts`',
    'turns it into these steps, run in order by `src/engine/executor.ts`:',
    '',
    '| Step | What it does |',
    '| --- | --- |',
    ...STEP_TYPES.map(([type, what]) => `| \`${type}\` | ${what} |`),
    '',
    'When a step is too big to answer at once, the executor slices it (see [Probes](#probes)) and runs',
    'the same query once per slice, with the slice pinned in a `VALUES` block.',
    '',
  );
  for (const [name, title] of EXAMPLES) {
    const e = get(name);
    out.push(`### ${title}`, '', `Catalog entry \`${name}\`.`, '');
    e.steps.forEach((s, i) => {
      out.push(`#### Step ${i + 1}: ${s.description ?? s.type}`, '', `\`${s.type}\` on \`${s.endpoint}\``, '', ...fence(s.query), '');
    });
  }

  out.push(
    '### Details for each entity type',
    '',
    'What the hydrate step loads once the identifiers are known, per entity type.',
    '',
  );
  for (const [type, label] of ENTITY_LABELS) {
    const s = get(`${type} near samples [ME on A]`).steps.find((x) => x.type === 'HYDRATE_TARGET_BY_IRI')!;
    out.push(`#### ${label}, on \`${s.endpoint}\``, '', ...fence(s.query), '');
  }

  const probes = entries.filter((e) => e.name.startsWith('PROBE: '));
  out.push(
    '## Probes',
    '',
    `Sent from ${probes[0].usedBy}. A probe lists up to 201 entities on one side of the question, which`,
    'decides whether the work can be sliced by entity or has to be sliced by county.',
    '',
  );
  for (const [type, label] of ENTITY_LABELS) {
    const e = get(`PROBE: ${type}`);
    out.push(`#### ${label}, on \`${e.steps[0].endpoint}\``, '', ...fence(e.steps[0].query), '');
  }

  out.push('## Prefixes', '', 'Prepended to every query above, from `src/constants/prefixes.ts`.', '', '```sparql', PREFIXES.trim().split('\n').map((l) => l.trim()).join('\n'), '```', '');
  return out.join('\n');
}

// One page per dashboard question, in docs/queries/<id>.md.
export function renderQuestionPage(prebuilt: PrebuiltQuery, entry: CatalogEntry): string {
  const { blockA, relationship, blockC } = prebuilt.question;
  const rel =
    relationship.type === 'near'
      ? `Near (${relationship.hops ?? 1} hop${(relationship.hops ?? 1) === 1 ? '' : 's'})`
      : `${capitalise(relationship.type)}${relationship.maxDistanceKm ? `, within ${relationship.maxDistanceKm} km of flow` : ''}`;
  const out = [
    `# ${prebuilt.title}`,
    '',
    `<!-- Generated by src/engine/queries/catalog.test.ts from src/constants/prebuiltQueries.ts. Do not edit by hand: run \`npm test -- -u\`. -->`,
    '',
    `> ${prebuilt.description}`,
    '',
    `**ID**: \`${prebuilt.id}\`, one of the dashboard questions.`,
    '',
    '## Analysis question',
    '',
    '| Part | Configuration |',
    '| --- | --- |',
    `| **Block A** | ${describeBlock(blockA)} |`,
    `| **Relationship** | ${rel} |`,
    `| **Block C** | ${describeBlock(blockC)} |`,
    '',
    '## Pipeline steps',
    '',
    'As the engine plans it today. Where a step receives identifiers from an earlier step, they appear',
    'as `http://example.org/...` placeholders. The shared PREFIX block is left out; see',
    '[docs/QUERIES.md](../QUERIES.md#prefixes).',
    '',
    '| # | Step | Endpoint | Shown in the app as |',
    '| --- | --- | --- | --- |',
    ...entry.steps.map((s, i) => `| ${i + 1} | \`${s.type}\` | \`${s.endpoint}\` | ${s.description ?? ''} |`),
    '',
    '## SPARQL',
    '',
  ];
  entry.steps.forEach((s, i) => out.push(`### Step ${i + 1}: ${s.description ?? s.type}`, '', ...fence(s.query), ''));
  return out.join('\n');
}

function describeBlock(block: EntityBlock): string {
  const parts: string[] = [block.type];
  const r = block.region;
  if (r?.countyCodes?.length) parts.push(`in ${r.countyCodes.map((c) => r.countyLabels?.[c] ?? c).join(', ')}`);
  else if (r?.stateCode) parts.push(`in state ${r.stateCode}`);
  const f = block.facilityFilters;
  if (f?.industryCodes?.length) parts.push(`NAICS ${f.industryCodes.map((c) => (f.industryLabels?.[c] ? `${c} (${f.industryLabels[c]})` : c)).join(', ')}`);
  const sf = block.sampleFilters;
  if (sf?.substances?.length) parts.push(`substances ${sf.substances.map((u) => sf.substanceLabels?.[u] ?? u.split('/').pop()).join(', ')}`);
  if (sf?.materialTypes?.length) parts.push(`material ${sf.materialTypes.map((u) => u.split(/[#/.]/).pop()).join(', ')}`);
  if (sf?.minConcentration != null || sf?.maxConcentration != null) parts.push(`${sf.minConcentration ?? 0} to ${sf.maxConcentration ?? 'any'} ${sf.unit ?? 'ng/L'}`);
  if (sf?.includeNondetects === false) parts.push('detections only');
  const other = [block.waterBodyFilters, block.wellFilters, block.aquiferFilters, block.streamFilters].filter(
    (x) => x && Object.values(x).some((v) => (Array.isArray(v) ? v.length : v != null)),
  );
  if (other.length) parts.push(`filters ${other.map((x) => JSON.stringify(x)).join(', ')}`);
  return parts.join(', ');
}

const capitalise = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

// GitHub's heading anchors: lowercase, punctuation dropped, spaces to hyphens.
const slug = (title: string) =>
  title
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, '')
    .replace(/ /g, '-');
