// The golden-file format for the catalog, and the diff between two of them.
//
// One line per step (`TYPE [endpoint] hash`) under a `## name` heading, then
// every distinct query body once, keyed by hash. 375 shapes reference about
// 2,000 step queries but only about 600 distinct ones (the region-boundary
// query alone is identical in 373 of them), so inlining every body made the
// file 2.6x larger and turned a one-line change to a shared query into 373
// lines of diff.
import { createHash } from 'node:crypto';
import { PREFIXES } from '../../constants/prefixes';
import type { CatalogEntry } from './catalog';

// Collapse whitespace: indentation churn is not a behaviour change and would
// bury the diffs that are.
//
// The shared PREFIX preamble is stripped for the same reason, plus one of its
// own: it is byte-identical in every query and was 66% of the file. It is
// recorded once, on its own, so a change to the prefix list still shows up as
// exactly one moved entry instead of moving every one.
const collapse = (q: string) => q.replace(/\s+/g, ' ').trim();
const PREFIX_BLOCK = collapse(PREFIXES);
const normalise = (q: string) => collapse(q).replace(PREFIX_BLOCK, '').trim();
const hash = (s: string) => createHash('sha256').update(s).digest('hex').slice(0, 12);

export const BODIES_MARKER = '# ---- query bodies, one line per distinct query ----';

export function renderSnapshot(entries: CatalogEntry[]): string {
  const bodies = new Map<string, string>();
  const out = [
    '# Generated by src/engine/queries/catalog.test.ts -- do not hand-edit.',
    '# Re-record with: npm test -- -u',
    '',
    '## PREFIXES',
    `SHARED [all] ${hash(PREFIX_BLOCK)}`,
    `  ${PREFIX_BLOCK}`,
  ];
  for (const entry of entries) {
    out.push(`## ${entry.name}`);
    for (const step of entry.steps) {
      const query = normalise(step.query);
      if (!query) throw new Error(`empty query: ${entry.name} / ${step.type}`);
      const h = hash(query);
      bodies.set(h, query);
      out.push(`${step.type} [${step.endpoint}] ${h}`);
    }
  }
  // Sorted by hash so the table has a stable order and a new query lands as
  // one added line rather than reshuffling the file.
  out.push('', BODIES_MARKER);
  for (const [h, query] of [...bodies].sort(([a], [b]) => a.localeCompare(b))) out.push(`${h} ${query}`);
  return out.join('\n') + '\n';
}

// Shapes only: the body table is keyed by content hash, so any change to a
// query already moves the hash of every shape that references it.
function headings(text: string): Map<string, string> {
  const map = new Map<string, string>();
  let current = '';
  for (const line of text.split('\n')) {
    if (line === BODIES_MARKER) break;
    if (line.startsWith('## ')) current = line.slice(3);
    else if (current) map.set(current, (map.get(current) ?? '') + line + '\n');
  }
  return map;
}

export interface BlastRadius {
  total: number;
  moved: string[];
  added: string[];
  removed: string[];
}

export function blastRadius(before: string, after: string): BlastRadius {
  const a = headings(before);
  const b = headings(after);
  return {
    total: b.size,
    moved: [...b.keys()].filter((k) => a.has(k) && a.get(k) !== b.get(k)),
    added: [...b.keys()].filter((k) => !a.has(k)),
    removed: [...a.keys()].filter((k) => !b.has(k)),
  };
}

// Bucketed by every axis of the grid, not just the relationship: a change that
// moves only the bounded shapes, or only the ones scoped on block C, is saying
// something quite different from one that moves a whole relationship.
const BUCKETS: Array<[string, RegExp]> = [
  ['near', / near /],
  ['downstream', / downstream[( ]/],
  ['upstream', / upstream[( ]/],
  ['bounded', /\(30km\)/],
  ['region on A', /\[ME on A\]/],
  ['region on C', /\[ME on C\]/],
  ['variants', /^VARIANT/],
  ['dropdowns', /^DROPDOWN/],
  ['popups', /^POPUP/],
  ['probes', /^PROBE/],
];

export function formatBlastRadius(r: BlastRadius, limit = 40): string {
  const changed = r.moved.length + r.added.length + r.removed.length;
  if (!changed) return `No query changed. All ${r.total} catalog entries generate the same SPARQL.`;
  const lines = [
    `${r.moved.length} of ${r.total} catalog entries generate different SPARQL` +
      (r.added.length ? `, ${r.added.length} added` : '') +
      (r.removed.length ? `, ${r.removed.length} removed` : '') +
      '.',
    '',
    '| ' + BUCKETS.map(([name]) => name).join(' | ') + ' |',
    '|' + BUCKETS.map(() => ' ---: |').join(''),
    '| ' + BUCKETS.map(([, re]) => r.moved.filter((n) => re.test(n)).length).join(' | ') + ' |',
    '',
  ];
  const list = (title: string, names: string[]) => {
    if (!names.length) return;
    lines.push(`${title}:`);
    for (const n of names.slice(0, limit)) lines.push(`- ${n}`);
    if (names.length > limit) lines.push(`- ... and ${names.length - limit} more`);
    lines.push('');
  };
  list('Changed', r.moved);
  list('Added', r.added);
  list('Removed', r.removed);
  return lines.join('\n');
}
